### ISSUE TITLE
rename hashCode() to hash()

### ISSUE THREAD

**Issue by danielgaooooo** [TomPeng19971208/CS4500_A1_Part2#3]
please rename your hashCode() method in your object class to hash() to match the spec prof vitek started in class, thanks homies

**Comment by TomPeng19971208** [comment]
Hi, sry for the inconvenience. I've removed implementation in object.h, string.h, and all other files. I've also changed the signature and name of hashCode() to match the professor's spec. Please dont hesitate to let me know if you have other requests, I will check Github issues regularly.

**Comment by danielgaooooo** [comment]
Thanks!
