### ISSUE TITLE
Incorrectly named functions in test-hashmap.cpp

### ISSUE THREAD

**Issue by thomas-vaiarella** [TomPeng19971208/CS4500_A1_Part2#8]
Lines 117-119, containsKey should be contains_key
Lines 176, 191, get_cap should be capacity
Line 211, keys should be key_set

Additionally, the member variable _capacity_ and the function _capacity_ seem to conflict, making it so _capacity()_ cannot be publicly invoked on an instance of a Hashmap

**Comment by TomPeng19971208** [comment]
changed it to get_capacity()
